# Conteúdo do arquivo dependabot.yml com configuração para NuGet em projeto .NET
dependabot_yml = """
# Dependabot configuration for BookSpaceApi (.NET + NuGet + GitHub Actions)
version: 2
updates:
  # Atualiza pacotes NuGet (projeto .NET)
  - package-ecosystem: "nuget"
    directory: "/" # Local dos arquivos .csproj ou .sln
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # (Opcional) Atualiza GitHub Actions, se utilizado no repositório
  - package-ecosystem: "github-actions"
    directory: "/" # Raiz do repositório
    schedule:
      interval: "monthly"
"""

# Salvar o conteúdo em um arquivo .yml
dependabot_path = "/mnt/data/dependabot.yml"
with open(dependabot_path, "w", encoding="utf-8") as f:
    f.write(dependabot_yml)

dependabot_path

